image: docker.slock.it/build-images/node:11-alpine
variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
stages:
  - test

test-parity:
  stage: test
  tags:
    - short-jobs
  services:
    - docker:dind
    
  script:
    - sh /prepare.sh
    - export DOCKER_HOST=tcp://docker:2375
    - apk add docker
    - docker pull ethereum/solc:0.5.10 
    - npm install
    - ./node_modules/truffle/build/cli.bundled.js compile
    - ./node_modules/truffle/build/cli.bundled.js migrate --network CI
    - ./node_modules/truffle/build/cli.bundled.js test --network CI

  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report
