image: docker.slock.it/build-images/node:11-alpine
variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
stages:
  - lint
  - test

lint-contracts-solium:
  stage: lint
  tags:
    - short-jobs
  script: 
    - sh /prepare.sh
    - npm i ethlint
    - npm run lint:solium

lint-contracts-solhint:
  stage: lint
  tags:
    - short-jobs
  script: 
    - sh /prepare.sh
    - npm i solhint
    - npm run lint:solhint

test-parity:
  stage: test
  tags:
    - short-jobs
  variables:
    RPCURL: http://blockchainclient:8545
    IPFS_URL: http://ipfs:5001
  services:
    - name: jbenet/go-ipfs:latest
      command:
        - daemon
        - --offline
      alias: ipfs
    - name: docker.slock.it/core-technology/parity-timemachine:master
      alias: blockchainclient
  script:
    - sh /prepare.sh
    - npm install
    - npm test

  artifacts:
    name: "test-reports-$CI_JOB_NAME"
    paths:
      - test/report
