image: docker.slock.it/build-images/node:11-alpine
variables:
  COMMIT_IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
stages:
  - lint
  - build
  - test
  - deploy
  
lint-contracts-solium:
  stage: lint
  tags:
    - short-jobs
  script: 
    - sh /prepare.sh
    - npm i ethlint
    - npm run lint:solium

lint-contracts-solhint:
  stage: lint
  tags:
    - short-jobs
  script: 
    - sh /prepare.sh
    - npm i solhint
    - npm run lint:solhint

compile-contracts:
  stage: build
  tags:
    - short-jobs
  services:
    - docker:dind
  image: docker.slock.it/build-images/deployment
  script:
    - docker run --rm -v $(pwd)/contracts:/contracts ethereum/solc:0.5.10 --optimize --combined-json abi,bin,bin-runtime,compact-format,hashes,interface,metadata,srcmap-runtime /contracts/NodeRegistry.sol /contracts/BlockhashRegistry.sol > contracts/contracts.json
  artifacts:
    paths:
      - contracts/contracts.json

test-parity:
  stage: test
  tags:
    - short-jobs
  services:
    - name: docker.slock.it/core-technology/parity-timemachine:master
      alias: blockchainclient
  script:
    - sh /prepare.sh
    - npm install
    - npm run compile
    - ./node_modules/truffle/build/cli.bundled.js migrate --network CI
    - ./node_modules/truffle/build/cli.bundled.js test --network CI

test-coverage:
  stage: test
  tags:
    - short-jobs
  script:
    - sh /prepare.sh
    - npm install
    - npm run coverage

push-to-slockit-registry:
  stage: deploy
  tags:
    - short-jobs
  only:
    - '/^v[0-9]*\.[0-9]*\.[0-9]*-?.*$/'
  except:
    - branches
  dependencies:
    - compile-contracts
  script:
    - sh /prepare.sh
    - npm --no-git-tag-version -f version $CI_COMMIT_TAG --allow-same-version
    - npm publish



